apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: synergychat-api
  ports:
    - nodePort: 30080
      port: 80
      targetPort: 8080 # port the PODS are listening to
